spring.application.name=notification-service
server.port=9080
spring.profiles.active=local
spring.webflux.base-path=/api/event

eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true
