#spring.config.import= optional:file:.env[.properties]

spring.application.name=notification-service
server.port=9080
spring.profiles.active=local
spring.webflux.base-path=/api/event

eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true

twilio.account_sid=${TWILIO_ACCOUNT_SID:}
twilio.auth_token=${TWILIO_AUTH_TOKEN:}
twilio.trial_number=${TWILIO_FROM_PHONE:}
special_number=${SPECIAL_NUMBERS}
jimi_number=${JIMI_NUMBER}